version: '3'

services:

  web:
    image: westside072/php-fpm:7.4.26
    volumes:
      - .:/var/www
      - ./docker/php-fpm/php.ini:/etc/php/8.1/fpm/php.ini
      - ./docker/php-fpm/php.ini:/etc/php/8.1/cli/php.ini
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - 8000:8000
    depends_on:
      - mysqldb

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - mysqldb

  mysqldb:
    image: jamielsharief/mysql:latest #for m1 macs
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

